First branch- all code
SapirCardona/Final-project pull request #1
Opened 2021-05-24 16:28 UTC by SapirCardona

2021-05-31 09:34 UTC, morsoffer requested changes
Well Done 💪🤩 
See my comments. We can talk about them today in the meeting 🙂

2021-05-31 09:34 UTC, morsoffer commented on POC.py
> +
please remove all these empty lines

2021-05-31 09:34 UTC, morsoffer commented on POC.py
> +add_to_shopping_bag("nike", "man", "shirt", "M")
I guess all these lines are for your testing. please remove them before you publish a PR

2021-05-31 09:34 UTC, morsoffer commented on Templates/index.html
> +        </li>
Why do you need to add it to every HTML file? 
And if this is the only way to do that, check if you can make an HTML file with only this code and add it to this file.

2021-05-31 09:34 UTC, morsoffer commented on Templates/POC page.html
> +<!doctype html>
add `_` in the name of the file instead of a space. it can lead to unexpected behaviours

2021-05-31 09:34 UTC, morsoffer commented on Templates/To_use.html
> +  <div class="btn-group-vertical">
what is the purpose of this file? the name of the file is not indicative

2021-05-31 09:34 UTC, morsoffer commented on Templates/To_use.html
> +    <button type="button" class="btn btn-dark">{{  categories.0  }}</button>
I saw you already put this code in other HTML files. I think you can import it to there as a component

2021-05-31 09:34 UTC, morsoffer commented on framework.py
> +from Sapir.Finalproject import POC
I think you can remove the `from Sapir.Finalproject` and just do the import

2021-05-31 09:34 UTC, morsoffer commented on framework.py
> +
add `pass` here

2021-05-31 09:34 UTC, morsoffer commented on framework.py
> +
remove all these extra lines

2021-05-31 09:34 UTC, morsoffer commented on framework.py
> +@app.route("/add_to_shopping_bag")
you should read about routes in REST API. This is an article that explains about it: https://medium.com/@rajat_m/what-are-restful-routes-and-how-to-use-them-929129ae7bf6 
And I'll explain it anyway in the meeting today :)

2021-05-31 17:17 UTC, SapirCardona commented on Templates/index.html
> +        </li>
On it.

2021-05-31 18:37 UTC, SapirCardona commented on Templates/index.html
> +        </li>
Done.

2021-06-01 08:13 UTC, morsoffer commented
@SapirCardona I don't see your changes in the templates (with the blocks) that you worked on yesterday.

2021-06-01 12:48 UTC, SapirCardona commented on Templates/To_use.html
> +    <button type="button" class="btn btn-dark">{{  categories.0  }}</button>
Sounds about right. How do I do that?  hahaha

2021-06-01 12:51 UTC, SapirCardona reviewed
Im not sure I put the changes at the right branch.... 
How bad is it?

2021-06-02 07:18 UTC, morsoffer approved these changes
Good Job! 💃💃 
See my comments and change them accordingly. After that you can merge the branch to `main` (I prefer to squash the branch and not to merge - I'll explain why in the next meeting). To squash it you need to click on the arrow of the merge button at the bottom of the conversation file of this PR and choose squash. After that, click on the squash button :)

2021-06-02 07:18 UTC, morsoffer commented on Templates/POC_page.html
> +<script>
if you are adding `script` put it in one place - at the header of this HTML file. then all the javascript functions will be in one place in every HTML file.

2021-06-02 07:18 UTC, morsoffer commented on Templates/Sign.html
> +<html lang="en">
why is this HTML file doesn't extend the Base file as well?

2021-06-02 07:18 UTC, morsoffer commented on framework.py
> +@app.route("/add_to_shopping_bag")
we can change it together at the next meeting :)

2021-06-07 15:57 UTC, SapirCardona commented on Templates/Sign.html
> +<html lang="en">
I think I forgot.. hahaha. 
done :)

2021-06-07 15:58 UTC, SapirCardona commented on framework.py
> +@app.route("/add_to_shopping_bag")
Change what?

2021-06-07 17:19 UTC, merged